[package]
name = "neon-build"
version = "0.4.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Build logic required for Neon projects."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
build = "build.rs"

[dependencies]
neon-sys = { version = "=0.4.0", path = "../neon-sys", optional = true }
cfg-if = "0.1.9"

[build-dependencies]
cfg-if = "0.1.9"
